# Managing Group Policies {#manage}

Before diving into specific Group Policies, let's review the basics of managing Group Policy.

A Windows Active Directory Administrator should know that Group Policies are managed via the Group Policy Management Console (GPMC). Unfortunately there isn't a similar tool for Samba Active Directory Administrators. The Samba project does provide the comprehensive `samba-tool gpo` command, which supplants much of the GPMC.

There are instances where Samba's Group Policy can only be managed via the GPMC, with no `samba-tool gpo` alternative. These cases will be highlighted in the text.

## Creating a Group Policy Object {#gpcreate}

The `samba-tool gpo create` command is used to create a Group Policy Object.

```
> samba-tool gpo create --help
Usage: samba-tool gpo create <displayname> [options]

Create an empty GPO.
```

## Deleting a Group Policy Object {#gpdelete}

```
> samba-tool gpo del --help
Usage: samba-tool gpo del <gpo> [options]

Delete a GPO.
```

## Group Policy Links {#gplink}

```
> samba-tool gpo setlink --help
Usage: samba-tool gpo setlink <container_dn> <gpo> [options]

Add or update a GPO link to a container.
```

```
> samba-tool gpo dellink --help
Usage: samba-tool gpo dellink <container_dn> <gpo> [options]

Delete GPO link from a container.
```

## Listing a Group Policy {#gplist}

```
> samba-tool gpo list --help
Usage: samba-tool gpo list <username|machinename> [options]

List GPOs for an account.
```

## Modifying a Group Policy {#gpmodify}

The `samba-tool gpo manage` is used for modifying settings on a Group Policy Object. See the individual chapters for each subcommand explanation.

<table>
 <thead>
  <tr>
   <th style="text-align:left;">samba-tool command</th>
   <th style="text-align:left;">Chapter</th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td>`samba-tool gpo manage smb_conf`</td>
   <td>\@ref(smbconf)</td>
  </tr>
  <tr>
   <td>`samba-tool gpo manage security`</td>
   <td>\@ref(sec)</td>
  </tr>
  <tr>
   <td>`samba-tool gpo manage scripts`</td>
   <td>\@ref(scripts)</td>
  </tr>
  <tr>
   <td>`samba-tool gpo manage files`</td>
   <td>\@ref(files)</td>
  </tr>
  <tr>
   <td>`samba-tool gpo manage symlink`</td>
   <td>\@ref(symlink)</td>
  </tr>
  <tr>
   <td>`samba-tool gpo manage sudoers`</td>
   <td>\@ref(sudoers)</td>
  </tr>
  <tr>
   <td>`samba-tool gpo manage issue`</td>
   <td>\@ref(msgs)</td>
  </tr>
  <tr>
   <td>`samba-tool gpo manage motd`</td>
   <td>\@ref(msgs)</td>
  </tr>
  <tr>
   <td>`samba-tool gpo manage access`</td>
   <td>\@ref(pamaccess)</td>
  </tr>
  <tr>
   <td>`samba-tool gpo manage openssh`</td>
   <td>\@ref(openssh)</td>
  </tr>
</tbody>
</table>
